"""POST UPDATED

Revision ID: 5625915340e6
Revises: 5f3995565121
Create Date: 2020-06-03 15:23:51.405773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5625915340e6'
down_revision = '5f3995565121'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('email', sa.String(length=120), nullable=False))
    op.add_column('posts', sa.Column('first_name', sa.String(length=50), nullable=False))
    op.add_column('posts', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.add_column('posts', sa.Column('note', sa.String(length=280), nullable=True))
    op.add_column('posts', sa.Column('phone', sa.String(length=12), nullable=True))
    op.create_index(op.f('ix_posts_email'), 'posts', ['email'], unique=True)
    op.create_index(op.f('ix_posts_first_name'), 'posts', ['first_name'], unique=False)
    op.create_index(op.f('ix_posts_last_name'), 'posts', ['last_name'], unique=False)
    op.drop_column('posts', 'body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body', sa.VARCHAR(length=280), nullable=True))
    op.drop_index(op.f('ix_posts_last_name'), table_name='posts')
    op.drop_index(op.f('ix_posts_first_name'), table_name='posts')
    op.drop_index(op.f('ix_posts_email'), table_name='posts')
    op.drop_column('posts', 'phone')
    op.drop_column('posts', 'note')
    op.drop_column('posts', 'last_name')
    op.drop_column('posts', 'first_name')
    op.drop_column('posts', 'email')
    # ### end Alembic commands ###
