"""POST UPDATED

Revision ID: e9cc135f7961
Revises: 5625915340e6
Create Date: 2020-06-03 15:37:22.227096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9cc135f7961'
down_revision = '5625915340e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=12), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('note', sa.String(length=280), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_email'), 'posts', ['email'], unique=True)
    op.create_index(op.f('ix_posts_first_name'), 'posts', ['first_name'], unique=False)
    op.create_index(op.f('ix_posts_last_name'), 'posts', ['last_name'], unique=False)
    op.create_index(op.f('ix_posts_timestamp'), 'posts', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_timestamp'), table_name='posts')
    op.drop_index(op.f('ix_posts_last_name'), table_name='posts')
    op.drop_index(op.f('ix_posts_first_name'), table_name='posts')
    op.drop_index(op.f('ix_posts_email'), table_name='posts')
    op.drop_table('posts')
    # ### end Alembic commands ###
